name: Lint

on:
  workflow_call:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: |
          npm init -y 
          npm i eslint eslint-config-semistandard eslint-config-prettier prettier eslint-config-standard eslint-plugin-import eslint-plugin-n eslint-plugin-promise
          echo 'module.exports = {	"env": {		"browser": true,		"es2021": true	},	"extends": [        "semistandard",        "prettier"    ],	"overrides": [	],	"parserOptions": {		"ecmaVersion": "latest"	}};' > .eslintrc.js

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          auto_fix: true
          eslint: true
          eslint_extensions: js
          eslint_dir: ./www
          prettier: true
          prettier_extensions: js
          prettier_dir: ./www
