name: Check and Deploy

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write # write to repo the lint changes
  pages: write # allow deploy to pages
  id-token: write
  checks: write # allow linter to make comments on commits

jobs:
  run-linters:
    uses: ./.github/workflows/linters.yml
  deploy:
    needs: run-linters
    uses: ./.github/workflows/static.yml
